### ISSUE TITLE
ERROR: Service 'Emulator-Appium' failed to build : Build failed

### ISSUE THREAD

**Issue by MohabMohie** [Amrkamel1/Android-Emulator-Docker#1]
When I try to use the docker-compose file I get this error. Here are some screenshots from the file and failed command:

![image](https://user-images.githubusercontent.com/19201898/132329599-cc38a29a-ed70-4423-b97f-8d2f6cafd664.png)
![image](https://user-images.githubusercontent.com/19201898/132329700-a906c6e6-b035-4430-a573-90d1ed485dc2.png)

Environment:
Windows 10 x64
IntelliJ 2021.2.1
Docker Engine 20.10.8

**Comment by Amrkamel1** [comment]
Thanks @MohabMohie  for pointing out to this issue 

Did you change these params with your relevant once 

```
      branch: master                        ##REPO BRANCH NAME
      username: amrka                       ##Github Username
      gitPass: password                     ##Github password
      gitUrl: github.com/amrka/API-test.git ## Repo SSH URL 
```

this should be used in case you want to pull your repo inside the container and execute you test inside.

**Comment by MohabMohie** [comment]
I didn't change them no... Didn't know what these settings were used for so I tried running it out of the box.
Glad I attached a screenshot 😀

Okay, so if I just want the grid to run, I should remove these params?

I can then run my code the traditional way and connect it to localhost:4444 to run remotely, right?

**Comment by MohabMohie** [comment]
after removing these lines entirely a similar error is shown
![image](https://user-images.githubusercontent.com/19201898/132502937-594da0c4-692f-4e76-b789-8bd3420d2548.png)

**Comment by Amrkamel1** [comment]
@MohabMohie  Thanks for raising this issue,

there is a completely new image will be pushed in a couple of days, it will have a lot of major enhancements, service, and upgrades.

So stay tuned :)

**Comment by Amrkamel1** [comment]
@MohabMohie 
please pull the latest image, and check the latest docker-compose file.

**Comment by MohabMohie** [comment]
after updating to the latest docker-compose file and removing the block that checks-out test code
![image](https://user-images.githubusercontent.com/19201898/132977440-c5fc2d40-d857-4960-aa0d-ea3c5bde8535.png)

**Comment by Amrkamel1** [comment]
@MohabMohie  that's odd, probably not related to the image itself could you run  the following in the same root, and revert the name of the compose file to the default one  "docker-compose" :

```
$docker-compose down -v --rmi all --remove-orphans
$ docker rm -v $(docker ps -aq -f 'status=exited')
$ docker rmi $(docker images -aq -f 'dangling=true')
```

then add in then add tag latest to the image in docker-compose   image: amrka/ultimate-android:latest

then run 

`$ docker-compose up `

**Comment by Amrkamel1** [comment]
Closed due to inactivity
