### ISSUE TITLE
Dockerfile request

### ISSUE THREAD

**Issue by NikTheGeek1** [Amrkamel1/Android-Emulator-Docker#2]
Hey man, thanks for the image. Great job and almost an ideal solution for my problem at hand. I am just writing to ask if I can have a peek in your Dockerfile --I am trying to do something similar but keep getting errors. I just need some inspiration. 

Thank you.

**Comment by Amrkamel1** [comment]
@NikTheGeek1 
Thanks nik for the comment, could you share your dockerfile and the errors you are getting, maybe i can help you.

**Comment by NikTheGeek1** [comment]
I was just trying to build a react-native environment from which I'd build a react-native app and install it to an emulator. This approach gave me more obstacles than the free time I got, so I decided to find a different way. At the end, I am building the app and installing it to a real android device from within the container. In other words, instead of an emulator I use a real android device. But thanks for the offer to help, and apologies if that wasn't the appropriate place to ask such a question :)
Good luck ✌️
